/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Presentacion;

import Negocio.DoctorControl;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.TableRowSorter;


public class FrmDoctores extends javax.swing.JInternalFrame {
    private final DoctorControl CONTROL;
    private String accion;
    private String nombreAnt;
    /**
     * Creates new form FrmDoctores
     */
    public FrmDoctores() {
        initComponents();
        this.CONTROL=new DoctorControl();
        this.listar("");
        this.accion = "Guardar";
        //Listado.setEnabled(true);
        Tabgeneral.setEnabledAt(1,false);
        
        txtBuscar.getDocument().addDocumentListener(new DocumentListener() {
            public void insertUpdate(DocumentEvent e) {
                listar(txtBuscar.getText());
            }

            public void removeUpdate(DocumentEvent e) {
                listar(txtBuscar.getText()); 
            }

            public void changedUpdate(DocumentEvent e) {
                //no se usa con JTextField
            }
        });
    }
    
    private void listar(String texto){
        Listado.setModel(this.CONTROL.listar(texto));
        TableRowSorter orden = new TableRowSorter(Listado.getModel());
        Listado.setRowSorter(orden);
        txtTotal.setText("Mostrando " + this.CONTROL.totalMostrados() + " de un total de " + this.CONTROL.total() + " registros"); 
    }
    
    private void mensajeError(String mensaje){
        JOptionPane.showMessageDialog(this,mensaje,"ERROR",JOptionPane.ERROR_MESSAGE);
    }
    
    private void mensajeOk(String mensaje){
        JOptionPane.showMessageDialog(this,mensaje,"Éxito",JOptionPane.INFORMATION_MESSAGE);
    }
    
    public void validarDNI(){
        
        if(txtNombreDoctor.getText().isEmpty()){
            lblMensaje.setText("Campo Obligatorio");    
        }else{
            lblMensaje.setText("");
        }
        
        if(txtNombreDoctor.getText().isEmpty()){
            btnGuardar.setEnabled(false);
        }else{
            btnGuardar.setEnabled(true);
        }               
    }
    
    public void validarNombre(){
        
        if(txtDniDoctor.getText().isEmpty()){
            lblMensaje1.setText("Campo Obligatorio");    
        }else{
            lblMensaje1.setText("");
        }
        
        if(txtDniDoctor.getText().isEmpty()){
            btnGuardar.setEnabled(false);
        }else{
            btnGuardar.setEnabled(true);
        }               
    }
    
    public void validarTelefono(){
        
        if(txtTelefonoDoctor.getText().isEmpty()){
            lblMensaje2.setText("Campo Obligatorio");    
        }else{
            lblMensaje2.setText("");
        }
        
        if(txtTelefonoDoctor.getText().isEmpty()){
            btnGuardar.setEnabled(false);
        }else{
            btnGuardar.setEnabled(true);
        }               
    }
    
    
    
    public void validarCorreo(){
        
        if(txtCorreoDoctor.getText().isEmpty()){
            lblMensaje4.setText("Campo Obligatorio");    
        }else{
            lblMensaje4.setText("");
        }
        
        if(txtCorreoDoctor.getText().isEmpty()){
            btnGuardar.setEnabled(false);
        }else{
            btnGuardar.setEnabled(true);
        }               
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Tabgeneral = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        btnRegistrar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Listado = new javax.swing.JTable();
        btnActivar = new javax.swing.JButton();
        btnDesactivar = new javax.swing.JButton();
        txtTotal = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtNombreDoctor = new javax.swing.JTextField();
        txtDniDoctor = new javax.swing.JTextField();
        txtTelefonoDoctor = new javax.swing.JTextField();
        txtCorreoDoctor = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        lblMensaje = new javax.swing.JLabel();
        lblMensaje1 = new javax.swing.JLabel();
        lblMensaje2 = new javax.swing.JLabel();
        lblMensaje3 = new javax.swing.JLabel();
        lblMensaje4 = new javax.swing.JLabel();
        txtId = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Doctores");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/Presentacion/Imagenes/pacientes.png"))); // NOI18N

        Tabgeneral.setBackground(new java.awt.Color(255, 102, 0));

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));

        jLabel1.setText("Nombre del Doctor(a): ");

        txtBuscar.setForeground(new java.awt.Color(153, 153, 153));
        txtBuscar.setText("Buscar...");
        txtBuscar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtBuscarFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtBuscarFocusLost(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Presentacion/Imagenes/buscar.png"))); // NOI18N
        jButton1.setText("BUSCAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnRegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Presentacion/Imagenes/registro.png"))); // NOI18N
        btnRegistrar.setText("Registrar Doctor(a)");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Presentacion/Imagenes/edit.png"))); // NOI18N
        btnEditar.setText("Editar Doctor(a)");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        Listado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(Listado);

        btnActivar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Presentacion/Imagenes/check.png"))); // NOI18N
        btnActivar.setText("Activar Doctr(a)");
        btnActivar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActivarActionPerformed(evt);
            }
        });

        btnDesactivar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Presentacion/Imagenes/off.png"))); // NOI18N
        btnDesactivar.setText("Desactivar Doctor(a)");
        btnDesactivar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDesactivarActionPerformed(evt);
            }
        });

        txtTotal.setText("Total de Registros:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnDesactivar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnActivar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnRegistrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnEditar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnDesactivar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnActivar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        Tabgeneral.addTab("Listado de Doctores", jPanel2);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("DNI");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Nombre");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Teléfono");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Correo");

        txtNombreDoctor.setForeground(new java.awt.Color(153, 153, 153));
        txtNombreDoctor.setText("Escriba aquí...");
        txtNombreDoctor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNombreDoctorFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNombreDoctorFocusLost(evt);
            }
        });
        txtNombreDoctor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNombreDoctorKeyReleased(evt);
            }
        });

        txtDniDoctor.setForeground(new java.awt.Color(153, 153, 153));
        txtDniDoctor.setText("Escriba aquí...");
        txtDniDoctor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtDniDoctorFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDniDoctorFocusLost(evt);
            }
        });
        txtDniDoctor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDniDoctorKeyReleased(evt);
            }
        });

        txtTelefonoDoctor.setForeground(new java.awt.Color(153, 153, 153));
        txtTelefonoDoctor.setText("Escriba aquí...");
        txtTelefonoDoctor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtTelefonoDoctorFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTelefonoDoctorFocusLost(evt);
            }
        });
        txtTelefonoDoctor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTelefonoDoctorKeyReleased(evt);
            }
        });

        txtCorreoDoctor.setForeground(new java.awt.Color(153, 153, 153));
        txtCorreoDoctor.setText("Escriba aquí...");
        txtCorreoDoctor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCorreoDoctorFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCorreoDoctorFocusLost(evt);
            }
        });
        txtCorreoDoctor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCorreoDoctorKeyReleased(evt);
            }
        });

        btnGuardar.setBackground(new java.awt.Color(255, 204, 204));
        btnGuardar.setFont(new java.awt.Font("Algerian", 0, 12)); // NOI18N
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Presentacion/Imagenes/guardar.png"))); // NOI18N
        btnGuardar.setText("GUARDAR");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnCancelar.setBackground(new java.awt.Color(255, 255, 153));
        btnCancelar.setFont(new java.awt.Font("Algerian", 0, 12)); // NOI18N
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Presentacion/Imagenes/cancelar.png"))); // NOI18N
        btnCancelar.setText("CANCELAR");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        lblMensaje.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        lblMensaje.setForeground(new java.awt.Color(255, 0, 0));
        lblMensaje.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblMensaje1.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        lblMensaje1.setForeground(new java.awt.Color(255, 0, 0));
        lblMensaje1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblMensaje2.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        lblMensaje2.setForeground(new java.awt.Color(255, 0, 0));
        lblMensaje2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblMensaje3.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        lblMensaje3.setForeground(new java.awt.Color(255, 0, 0));
        lblMensaje3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblMensaje4.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        lblMensaje4.setForeground(new java.awt.Color(255, 0, 0));
        lblMensaje4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMensaje1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDniDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblMensaje2, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblMensaje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtNombreDoctor, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(45, 45, 45)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(lblMensaje3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtTelefonoDoctor, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtCorreoDoctor)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGap(113, 113, 113)
                            .addComponent(lblMensaje4, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(37, 37, 37))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblMensaje3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNombreDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(txtTelefonoDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCorreoDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblMensaje1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblMensaje2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblMensaje4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtDniDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(90, 90, 90))
        );

        Tabgeneral.addTab("Registro de Doctores", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Tabgeneral)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Tabgeneral, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreDoctorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreDoctorKeyReleased
        // TODO add your handling code here:
        validarDNI();
    }//GEN-LAST:event_txtNombreDoctorKeyReleased

    private void txtDniDoctorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDniDoctorKeyReleased
        // TODO add your handling code here:
        validarNombre();
    }//GEN-LAST:event_txtDniDoctorKeyReleased

    private void txtTelefonoDoctorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoDoctorKeyReleased
        // TODO add your handling code here:
        validarTelefono();
    }//GEN-LAST:event_txtTelefonoDoctorKeyReleased

    private void txtCorreoDoctorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCorreoDoctorKeyReleased
        // TODO add your handling code here:
        validarCorreo();
    }//GEN-LAST:event_txtCorreoDoctorKeyReleased

    private void txtNombreDoctorFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNombreDoctorFocusGained
        // TODO add your handling code here:
        if(txtNombreDoctor.getText().equals("Escriba aquí...")){
            txtNombreDoctor.setText("");
        }
    }//GEN-LAST:event_txtNombreDoctorFocusGained

    private void txtNombreDoctorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNombreDoctorFocusLost
        // TODO add your handling code here:
        if(txtNombreDoctor.getText().isEmpty()){
            txtNombreDoctor.setText("Escriba aquí...");
        }
    }//GEN-LAST:event_txtNombreDoctorFocusLost

    private void txtDniDoctorFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDniDoctorFocusGained
        // TODO add your handling code here:
        if(txtDniDoctor.getText().equals("Escriba aquí...")){
            txtDniDoctor.setText("");
        }
    }//GEN-LAST:event_txtDniDoctorFocusGained

    private void txtDniDoctorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDniDoctorFocusLost
        // TODO add your handling code here:
        if(txtDniDoctor.getText().isEmpty()){
            txtDniDoctor.setText("Escriba aquí...");
        }
    }//GEN-LAST:event_txtDniDoctorFocusLost

    private void txtTelefonoDoctorFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTelefonoDoctorFocusGained
        // TODO add your handling code here:
        if(txtTelefonoDoctor.getText().equals("Escriba aquí...")){
            txtTelefonoDoctor.setText("");
        }
    }//GEN-LAST:event_txtTelefonoDoctorFocusGained

    private void txtTelefonoDoctorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTelefonoDoctorFocusLost
        // TODO add your handling code here:
        if(txtTelefonoDoctor.getText().isEmpty()){
            txtTelefonoDoctor.setText("Escriba aquí...");
        }
    }//GEN-LAST:event_txtTelefonoDoctorFocusLost

    private void txtCorreoDoctorFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCorreoDoctorFocusGained
        // TODO add your handling code here:
        if(txtCorreoDoctor.getText().equals("Escriba aquí...")){
            txtCorreoDoctor.setText("");
        }
    }//GEN-LAST:event_txtCorreoDoctorFocusGained

    private void txtCorreoDoctorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCorreoDoctorFocusLost
        // TODO add your handling code here:
        if(txtCorreoDoctor.getText().isEmpty()){
            txtCorreoDoctor.setText("Escriba aquí...");
        }
    }//GEN-LAST:event_txtCorreoDoctorFocusLost

    private void txtBuscarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBuscarFocusGained
        // TODO add your handling code here:
        if(txtBuscar.getText().equals("Buscar...")){
            txtBuscar.setText("");
        }
    }//GEN-LAST:event_txtBuscarFocusGained

    private void txtBuscarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBuscarFocusLost
        // TODO add your handling code here:
        if(txtBuscar.getText().isEmpty()){
            txtBuscar.setText("Buscar...");
        }
    }//GEN-LAST:event_txtBuscarFocusLost

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.listar(txtBuscar.getText());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnActivarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActivarActionPerformed
        // TODO add your handling code here:
        if(Listado.getSelectedRowCount() == 1){
            String id = String.valueOf(Listado.getValueAt(Listado.getSelectedRow(),0));
            String nombre = String.valueOf(Listado.getValueAt(Listado.getSelectedRow(),0));
            if(JOptionPane.showConfirmDialog(this, "Deseas activar el registro: " + nombre + "?", "Activar",JOptionPane.YES_NO_OPTION)==0){
                String resp = this.CONTROL.activar(Integer.parseInt(id));
                if(resp.equals("OK")){
                    this.mensajeOk("Registro activado");
                    this.listar("");
                }else{
                    this.mensajeError(resp);
                }
            }
        }else{
            this.mensajeError("Seleciona 1 registro a activar");
        }
    }//GEN-LAST:event_btnActivarActionPerformed

    private void btnDesactivarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDesactivarActionPerformed
        // TODO add your handling code here:
        if(Listado.getSelectedRowCount() == 1){
            String id = String.valueOf(Listado.getValueAt(Listado.getSelectedRow(),0));
            String nombre = String.valueOf(Listado.getValueAt(Listado.getSelectedRow(),0));
            if(JOptionPane.showConfirmDialog(this, "Deseas desactivar el registro: " + nombre + "?", "Desactivar",JOptionPane.YES_NO_OPTION)==0){
                String resp = this.CONTROL.desactivar(Integer.parseInt(id));
                if(resp.equals("OK")){
                    this.mensajeOk("Registro desactivado");
                    this.listar("");
                }else{
                    this.mensajeError(resp);
                }
            }
        }else{
            this.mensajeError("Seleciona 1 registro a desactivar");
        }
    }//GEN-LAST:event_btnDesactivarActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // TODO add your handling code here:
        Tabgeneral.setEnabledAt(1, true);
        Tabgeneral.setEnabledAt(0, false);
        Tabgeneral.setSelectedIndex(1);
        this.accion = "Guardar";
        btnGuardar.setText("Guardar");
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        Tabgeneral.setEnabledAt(0,true);
        Tabgeneral.setEnabledAt(1,false);
        Tabgeneral.setSelectedIndex(0);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        if(txtNombreDoctor.getText().length() == 0 || txtNombreDoctor.getText().length() > 20){
            JOptionPane.showMessageDialog(this, "Debes ingresar un nombre y no debe ser mayor a 50 caracteres, " + " es obligatorio",
                    "Advertencia",JOptionPane.WARNING_MESSAGE);
            txtNombreDoctor.requestFocus();
            return;
        }
        if(txtDniDoctor.getText().length() == 0 || txtDniDoctor.getText().length() > 255){
            JOptionPane.showMessageDialog(this, "Debes ingresar una descripción y no debe ser mayor a 10 caracteres, " + " es obligatorio",
                    "Advertencia",JOptionPane.WARNING_MESSAGE);
            txtDniDoctor.requestFocus();
            return;
        }
        
        if(txtTelefonoDoctor.getText().length() == 0 || txtTelefonoDoctor.getText().length() > 255){
            JOptionPane.showMessageDialog(this, "Debes ingresar una descripción y no debe ser mayor a 15 caracteres, " + " es obligatorio",
                    "Advertencia",JOptionPane.WARNING_MESSAGE);
            txtTelefonoDoctor.requestFocus();
            return;
        }
        
        if(txtCorreoDoctor.getText().length() == 0 || txtCorreoDoctor.getText().length() > 255){
            JOptionPane.showMessageDialog(this, "Debes ingresar una descripción y no debe ser mayor a 3 caracteres, " + " es obligatorio",
                    "Advertencia",JOptionPane.WARNING_MESSAGE);
            txtCorreoDoctor.requestFocus();
            return;
        }
        String resp;
        if(this.accion.equals("editar")){
            //Condicional para editar
            resp = this.CONTROL.actualizar(Integer.parseInt(txtId.getText()), txtNombreDoctor.getText(), nombreAnt, txtDniDoctor.getText(),
                    txtTelefonoDoctor.getText(),txtCorreoDoctor.getText());
            if(resp.equals("OK")){
                this.mensajeOk("Actualizado corectamente");
                this.listar("");
                Tabgeneral.setSelectedIndex(0);
                Tabgeneral.setEnabledAt(1, false);
                Tabgeneral.setEnabledAt(0, true);
            }else{
                this.mensajeError(resp);
            }
        }else{
            //condicional para guardar
            resp = this.CONTROL.insertar(txtNombreDoctor.getText(), txtDniDoctor.getText(),txtTelefonoDoctor.getText(),txtCorreoDoctor.getText());
            if(resp.equals("OK")){
                this.mensajeOk("Registrado corectamente");
                this.listar("");
                Tabgeneral.setSelectedIndex(0);
                Tabgeneral.setEnabledAt(1, false);
                Tabgeneral.setEnabledAt(0, true);
            }else{
                this.mensajeError(resp);
            }
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
        if(Listado.getSelectedRowCount() == 1){
            String id = String.valueOf(Listado.getValueAt(Listado.getSelectedRow(), 0));
            String nombre = String.valueOf(Listado.getValueAt(Listado.getSelectedRow(), 1));
            this.nombreAnt = String.valueOf(Listado.getValueAt(Listado.getSelectedRow(), 1));
            String DNI = String.valueOf(Listado.getValueAt(Listado.getSelectedRow(), 2));
            String telefono = String.valueOf(Listado.getValueAt(Listado.getSelectedRow(), 3));
            String correo = String.valueOf(Listado.getValueAt(Listado.getSelectedRow(), 4));
            
            txtId.setText(id);
            txtNombreDoctor.setText(nombre);
            txtDniDoctor.setText(DNI);
            txtTelefonoDoctor.setText(telefono);
            txtCorreoDoctor.setText(correo);
           
            Tabgeneral.setEnabledAt(0, false);
            Tabgeneral.setEnabledAt(1, true);
            Tabgeneral.setSelectedIndex(1);
            this.accion = "editar";
            btnGuardar.setText("Editar");
        }else{
            this.mensajeError("Selecionar 1 registro para editar");
        }
    }//GEN-LAST:event_btnEditarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Listado;
    private javax.swing.JTabbedPane Tabgeneral;
    private javax.swing.JButton btnActivar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnDesactivar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblMensaje;
    private javax.swing.JLabel lblMensaje1;
    private javax.swing.JLabel lblMensaje2;
    private javax.swing.JLabel lblMensaje3;
    private javax.swing.JLabel lblMensaje4;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtCorreoDoctor;
    private javax.swing.JTextField txtDniDoctor;
    private javax.swing.JLabel txtId;
    private javax.swing.JTextField txtNombreDoctor;
    private javax.swing.JTextField txtTelefonoDoctor;
    private javax.swing.JLabel txtTotal;
    // End of variables declaration//GEN-END:variables
}
