/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Presentacion;

/**
 *
 * @author Ruth Riveiro
 */
public class FrmPacientes extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmPacientes
     */
    public FrmPacientes() {
        initComponents();
    }
    
    public void validarDNI(){
        
        if(txtPaciente1.getText().isEmpty()){
            lblSolu.setText("Campo Obligatorio");    
        }else{
            lblSolu.setText("");
        }
        
        if(txtPaciente1.getText().isEmpty()){
            btnGuardar.setEnabled(false);
        }else{
            btnGuardar.setEnabled(true);
        }               
    }
    
    public void validarPaciente(){
        
        if(txtPaciente2.getText().isEmpty()){
            lblSolu1.setText("Campo Obligatorio");    
        }else{
            lblSolu1.setText("");
        }
        
        if(txtPaciente2.getText().isEmpty()){
            btnGuardar.setEnabled(false);
        }else{
            btnGuardar.setEnabled(true);
        }               
    }
    
    public void validarRaza(){
        
        if(txtPaciente3.getText().isEmpty()){
            lblSolu2.setText("Campo Obligatorio");    
        }else{
            lblSolu2.setText("");
        }
        
        if(txtPaciente3.getText().isEmpty()){
            btnGuardar.setEnabled(false);
        }else{
            btnGuardar.setEnabled(true);
        }               
    }
    
    public void validarEdad(){
        
        if(txtPaciente4.getText().isEmpty()){
            lblSolu3.setText("Campo Obligatorio");    
        }else{
            lblSolu3.setText("");
        }
        
        if(txtPaciente4.getText().isEmpty()){
            btnGuardar.setEnabled(false);
        }else{
            btnGuardar.setEnabled(true);
        }               
    }
    
    
    public void validarColor(){
        
        if(txtPaciente5.getText().isEmpty()){
            lblSolu4.setText("Campo Obligatorio");    
        }else{
            lblSolu4.setText("");
        }
        
        if(txtPaciente5.getText().isEmpty()){
            btnGuardar.setEnabled(false);
        }else{
            btnGuardar.setEnabled(true);
        }               
    }
    
    public void validarPeso(){
        
        if(txtPaciente6.getText().isEmpty()){
            lblSolu5.setText("Campo Obligatorio");    
        }else{
            lblSolu5.setText("");
        }
        
        if(txtPaciente6.getText().isEmpty()){
            btnGuardar.setEnabled(false);
        }else{
            btnGuardar.setEnabled(true);
        }               
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtPaciente1 = new javax.swing.JTextField();
        txtPaciente2 = new javax.swing.JTextField();
        txtPaciente4 = new javax.swing.JTextField();
        txtPaciente5 = new javax.swing.JTextField();
        txtPaciente3 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtPaciente6 = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        lblSolu = new javax.swing.JLabel();
        lblSolu1 = new javax.swing.JLabel();
        lblSolu2 = new javax.swing.JLabel();
        lblSolu3 = new javax.swing.JLabel();
        lblSolu4 = new javax.swing.JLabel();
        lblSolu5 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Pacientes");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/Presentacion/Imagenes/dog.png"))); // NOI18N

        jTabbedPane1.setBackground(new java.awt.Color(255, 102, 0));

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));

        jLabel1.setText("Nombre del Paciente: ");

        txtBuscar.setForeground(new java.awt.Color(153, 153, 153));
        txtBuscar.setText("Buscar...");
        txtBuscar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtBuscarFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtBuscarFocusLost(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Presentacion/Imagenes/buscar.png"))); // NOI18N
        jButton1.setText("BUSCAR");

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Presentacion/Imagenes/registro.png"))); // NOI18N
        jButton2.setText("Registrar Pacientes");

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Presentacion/Imagenes/edit.png"))); // NOI18N
        jButton3.setText("Editar Pacientes");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Presentacion/Imagenes/check.png"))); // NOI18N
        jButton4.setText("Activar Paciente");

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Presentacion/Imagenes/off.png"))); // NOI18N
        jButton5.setText("Desactivar Paciente");

        jLabel3.setText("Total de Registros:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(21, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Listado de Pacientes", jPanel1);

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("DNI");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Paciente");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Edad");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Color");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Raza");

        txtPaciente1.setForeground(new java.awt.Color(153, 153, 153));
        txtPaciente1.setText("Escriba aquí...");
        txtPaciente1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPaciente1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPaciente1FocusLost(evt);
            }
        });
        txtPaciente1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPaciente1KeyReleased(evt);
            }
        });

        txtPaciente2.setForeground(new java.awt.Color(153, 153, 153));
        txtPaciente2.setText("Escriba aquí...");
        txtPaciente2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPaciente2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPaciente2FocusLost(evt);
            }
        });
        txtPaciente2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPaciente2KeyReleased(evt);
            }
        });

        txtPaciente4.setForeground(new java.awt.Color(153, 153, 153));
        txtPaciente4.setText("Escriba aquí...");
        txtPaciente4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPaciente4FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPaciente4FocusLost(evt);
            }
        });
        txtPaciente4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPaciente4KeyReleased(evt);
            }
        });

        txtPaciente5.setForeground(new java.awt.Color(153, 153, 153));
        txtPaciente5.setText("Escriba aquí...");
        txtPaciente5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPaciente5FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPaciente5FocusLost(evt);
            }
        });
        txtPaciente5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPaciente5KeyReleased(evt);
            }
        });

        txtPaciente3.setForeground(new java.awt.Color(153, 153, 153));
        txtPaciente3.setText("Escriba aquí...");
        txtPaciente3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPaciente3FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPaciente3FocusLost(evt);
            }
        });
        txtPaciente3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPaciente3KeyReleased(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Peso");

        txtPaciente6.setForeground(new java.awt.Color(153, 153, 153));
        txtPaciente6.setText("Escriba aquí...");
        txtPaciente6.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPaciente6FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPaciente6FocusLost(evt);
            }
        });
        txtPaciente6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPaciente6KeyReleased(evt);
            }
        });

        btnGuardar.setBackground(new java.awt.Color(255, 204, 204));
        btnGuardar.setFont(new java.awt.Font("Algerian", 0, 12)); // NOI18N
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Presentacion/Imagenes/guardar.png"))); // NOI18N
        btnGuardar.setText("GUARDAR");

        jButton7.setBackground(new java.awt.Color(255, 255, 153));
        jButton7.setFont(new java.awt.Font("Algerian", 0, 12)); // NOI18N
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Presentacion/Imagenes/cancelar.png"))); // NOI18N
        jButton7.setText("CANCELAR");

        lblSolu.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        lblSolu.setForeground(new java.awt.Color(255, 0, 0));
        lblSolu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblSolu1.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        lblSolu1.setForeground(new java.awt.Color(255, 0, 0));
        lblSolu1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblSolu2.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        lblSolu2.setForeground(new java.awt.Color(255, 0, 0));
        lblSolu2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblSolu3.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        lblSolu3.setForeground(new java.awt.Color(255, 0, 0));
        lblSolu3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblSolu4.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        lblSolu4.setForeground(new java.awt.Color(255, 0, 0));
        lblSolu4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblSolu5.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        lblSolu5.setForeground(new java.awt.Color(255, 0, 0));
        lblSolu5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(78, 78, 78)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(lblSolu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtPaciente1, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblSolu2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtPaciente3)
                                    .addComponent(lblSolu1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtPaciente2, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(51, 51, 51)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(9, 9, 9))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPaciente6, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                            .addComponent(lblSolu4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblSolu5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtPaciente4, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSolu3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtPaciente5)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(38, 38, 38))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPaciente1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPaciente4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSolu, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lblSolu3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPaciente2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPaciente5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSolu1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSolu4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPaciente3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPaciente6, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblSolu2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblSolu5, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(209, 209, 209))
        );

        jTabbedPane1.addTab("Registro de Pacientes", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPaciente1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPaciente1KeyReleased
        // TODO add your handling code here:
        validarDNI();
    }//GEN-LAST:event_txtPaciente1KeyReleased

    private void txtPaciente2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPaciente2KeyReleased
        // TODO add your handling code here:
        validarPaciente();
    }//GEN-LAST:event_txtPaciente2KeyReleased

    private void txtPaciente3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPaciente3KeyReleased
        // TODO add your handling code here:
        validarRaza();
    }//GEN-LAST:event_txtPaciente3KeyReleased

    private void txtPaciente4KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPaciente4KeyReleased
        // TODO add your handling code here:
        validarEdad();
    }//GEN-LAST:event_txtPaciente4KeyReleased

    private void txtPaciente5KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPaciente5KeyReleased
        // TODO add your handling code here:
        validarColor();
    }//GEN-LAST:event_txtPaciente5KeyReleased

    private void txtPaciente6KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPaciente6KeyReleased
        // TODO add your handling code here:
        validarPeso();
    }//GEN-LAST:event_txtPaciente6KeyReleased

    private void txtBuscarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBuscarFocusGained
        // TODO add your handling code here:
        if (txtBuscar.getText().equals("Buscar...")) {
                    txtBuscar.setText("");
        }
    }//GEN-LAST:event_txtBuscarFocusGained

    private void txtBuscarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBuscarFocusLost
        // TODO add your handling code here:
        if (txtBuscar.getText().isEmpty()) {
                    txtBuscar.setText("Buscar...");
        }
    }//GEN-LAST:event_txtBuscarFocusLost

    private void txtPaciente1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPaciente1FocusGained
        // TODO add your handling code here:
        if(txtPaciente1.getText().equals("Escriba aquí...")){
            txtPaciente1.setText("");
        }
    }//GEN-LAST:event_txtPaciente1FocusGained

    private void txtPaciente1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPaciente1FocusLost
        // TODO add your handling code here:
        if(txtPaciente1.getText().isEmpty()){
            txtPaciente1.setText("Escriba aquí...");
        }
    }//GEN-LAST:event_txtPaciente1FocusLost

    private void txtPaciente2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPaciente2FocusGained
        // TODO add your handling code here:
        if(txtPaciente2.getText().equals("Escriba aquí...")){
            txtPaciente2.setText("");
        }
    }//GEN-LAST:event_txtPaciente2FocusGained

    private void txtPaciente2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPaciente2FocusLost
        // TODO add your handling code here:
        if(txtPaciente2.getText().isEmpty()){
            txtPaciente2.setText("Escriba aquí...");
        }
    }//GEN-LAST:event_txtPaciente2FocusLost

    private void txtPaciente3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPaciente3FocusGained
        // TODO add your handling code here:
        if(txtPaciente3.getText().equals("Escriba aquí...")){
            txtPaciente3.setText("");
        }
    }//GEN-LAST:event_txtPaciente3FocusGained

    private void txtPaciente3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPaciente3FocusLost
        // TODO add your handling code here:
        if(txtPaciente3.getText().isEmpty()){
            txtPaciente3.setText("Escriba aquí...");
        }
    }//GEN-LAST:event_txtPaciente3FocusLost

    private void txtPaciente4FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPaciente4FocusGained
        // TODO add your handling code here:
        if(txtPaciente4.getText().equals("Escriba aquí...")){
            txtPaciente4.setText("");
        }
    }//GEN-LAST:event_txtPaciente4FocusGained

    private void txtPaciente4FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPaciente4FocusLost
        // TODO add your handling code here:
        if(txtPaciente4.getText().isEmpty()){
            txtPaciente4.setText("Escriba aquí...");
        }
    }//GEN-LAST:event_txtPaciente4FocusLost

    private void txtPaciente5FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPaciente5FocusGained
        // TODO add your handling code here:
        if(txtPaciente5.getText().equals("Escriba aquí...")){
            txtPaciente5.setText("");
        }
    }//GEN-LAST:event_txtPaciente5FocusGained

    private void txtPaciente5FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPaciente5FocusLost
        // TODO add your handling code here:
        if(txtPaciente5.getText().isEmpty()){
            txtPaciente5.setText("Escriba aquí...");
        }
    }//GEN-LAST:event_txtPaciente5FocusLost

    private void txtPaciente6FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPaciente6FocusGained
        // TODO add your handling code here:
        if(txtPaciente6.getText().equals("Escriba aquí...")){
            txtPaciente6.setText("");
        }
    }//GEN-LAST:event_txtPaciente6FocusGained

    private void txtPaciente6FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPaciente6FocusLost
        // TODO add your handling code here:
        if(txtPaciente6.getText().isEmpty()){
            txtPaciente6.setText("Escriba aquí...");
        }
    }//GEN-LAST:event_txtPaciente6FocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblSolu;
    private javax.swing.JLabel lblSolu1;
    private javax.swing.JLabel lblSolu2;
    private javax.swing.JLabel lblSolu3;
    private javax.swing.JLabel lblSolu4;
    private javax.swing.JLabel lblSolu5;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtPaciente1;
    private javax.swing.JTextField txtPaciente2;
    private javax.swing.JTextField txtPaciente3;
    private javax.swing.JTextField txtPaciente4;
    private javax.swing.JTextField txtPaciente5;
    private javax.swing.JTextField txtPaciente6;
    // End of variables declaration//GEN-END:variables
}
